### ISSUE TITLE
0 themes in .santaregister is accepted but can't store to DynamoDB

### ISSUE THREAD

**Issue by glanyx** [glanyx/leegionbot-v2#4]
'put' request is trying to send themes as an empty string if 'done' is typed for themes as first input

Example request:
ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string
    at Request.extractError (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/ubuntu/leegionbot/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/ubuntu/leegionbot/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  message: 'One or more parameter values were invalid: An AttributeValue may not contain an empty string',
  code: 'ValidationException',
  time: 2019-11-29T18:48:17.752Z,
  requestId: '68AG76BBB584OL7RIMMN890J0NVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 32.91660445473005
}

**Comment by glanyx** [comment]
Fixed by forcing 1 or more themes as input
