### ISSUE TITLE
guildMemberAdd event unable to send message

### ISSUE THREAD

**Issue by glanyx** [glanyx/leegionbot-v2#5]
Unable to send message to configured channel. Likely caused by invalid fetching of channel by ID.

Couldn't send message to log. Invalid config?
TypeError: Cannot read property 'send' of undefined
    at require.module.exports (/home/ubuntu/leegionbot/src/events/guildMemberAdd.js:17:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by glanyx** [comment]
Confirmed now sending messages.
